FROM python:3.11-slim-bookworm

# Install Node.js and npm
RUN apt-get update && apt-get install -y \
  nginx \
  curl \
  libreoffice \
  fontconfig \
  chromium

# Install Node.js 20 using NodeSource repository
RUN curl -fsSL https://deb.nodesource.com/setup_20.x | bash - && \
  apt-get install -y nodejs


# Change working directory
WORKDIR /app

RUN ls -a

# Set environment variables
ENV APP_DATA_DIRECTORY=/app_data
ENV TEMP_DIRECTORY=/tmp/presenton
ENV PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium

# Install ollama
# RUN curl -fsSL http://ollama.com/install.sh | sh

# Install dependencies for FastAPI
RUN pip install aiohttp aiomysql aiosqlite asyncpg fastapi[standard] \
  pathvalidate pdfplumber sqlmodel fastembed-vectorstore \
  anthropic google-genai openai fastmcp dirtyjson requests
RUN pip install docling --extra-index-url https://download.pytorch.org/whl/cpu

# Install dependencies for OAuth service
WORKDIR /app/servers/oauth-service
COPY servers/oauth-service/package.json ./
COPY servers/oauth-service/package-lock.json* ./
COPY servers/oauth-service/patches/ ./patches/
RUN npm install

# Copy OAuth service
COPY servers/oauth-service/ /app/servers/oauth-service/

WORKDIR /app

# Copy nginx configuration
COPY nginx.conf /etc/nginx/nginx.conf

# Expose the port
EXPOSE 80

# Start the servers
CMD ["node", "/app/start.js", "--dev"]
